<?php

require_once('faq/faq.php');
require_once('hero_slider/hero-slider.php');
require_once('contact/contact.php');
require_once('reviews/reviews.php');
require_once('content/content.php');
require_once('hero_product/hero_product.php');
require_once('grid/grid.php');
require_once('product_card/product_card.php');
require_once('info_card/info_card.php');
require_once('hero_small/hero-small.php');
require_once('image_text/image-and-text.php');
require_once('call_to_action/cta.php');
require_once('hero_featured_insight/featured-insight-hero.php');
require_once('hero_home/hero-home.php');
require_once('vertical_text/vertical_text.php');
require_once('newsletter/newsletter.php');
require_once('product_guide_cta/product_guide_cta.php');
require_once('help_card/help_card.php');
require_once('international_contact/international_contact.php');
